### ISSUE TITLE
Import files and issues from amor-main

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/amor-configuration-files#1]
There are components at [amor-main](https://github.com/roboticslab-uc3m/amor-main) that probably do not belong to that repo, namely:

- [x] [AMOR API bindings](https://github.com/roboticslab-uc3m/amor-main/tree/c5570e4e5be64982d88f47d9d7d71724e03e2cf0/bindings) (https://github.com/roboticslab-uc3m/amor-main/issues/1)
- [x] [port arbitration Lua script](https://github.com/roboticslab-uc3m/amor-main/tree/c5570e4e5be64982d88f47d9d7d71724e03e2cf0/share) (https://github.com/roboticslab-uc3m/amor-main/issues/2)

Furthermore, YCM does not cope well with the YARP dependency required in `share/`.

**Comment by jgvictores** [comment]
While the [port arbitration Lua script](https://github.com/roboticslab-uc3m/amor-main/tree/c5570e4e5be64982d88f47d9d7d71724e03e2cf0/share) (https://github.com/roboticslab-uc3m/amor-main/issues/2) looks very amor-specific, perhaps it could make its way to [yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices)?

**Comment by PeterBowman** [comment]
Hmm right, I might have even written it in C++ (just like another YARP DL module library), which would make little sense in a &lt;robot&gt;-configuration-files repo. Where would you place it? Inside `libraries/YarpPlugins`?

**Comment by jgvictores** [comment]
From what I'm seeing, it is actually the [PortMonitor](http://www.yarp.it/portmonitor.html) carrier whom loads [C++](http://www.yarp.it/simple_dll.html)/[Lua](http://www.yarp.it/coder_decoder.html), so they are not plugins per se, more like a plugin-plugin (kind of reminds me of [this](http://snorks.wikia.com/wiki/Snorkeater-Eaters) situation).

If it were only Lua, I'd say `scripts/lua/`. However, to unify, I can only think of long ugly names/places:
- `libraries/YarpPortMonitorPlugins/`: too long.
- `libraries/YarpPlugins/PortMonitor/`: is counter-intuitive and even technically wrong.
- `libraries/YarpPlugins/PortMonitorPlugins/`: maybe?

Definitely open to suggestions!

**Comment by jgvictores** [comment]
Last option seems good, add cpp/lua subfolders too.

**Comment by PeterBowman** [comment]
Port monitor plugin done:

* issue: https://github.com/roboticslab-uc3m/amor-main/issues/2 moved to https://github.com/roboticslab-uc3m/yarp-devices/issues/177
* code:
   * https://github.com/roboticslab-uc3m/yarp-devices/commit/d26efda64ac7fcc4290e57894109e57e7368e904
   * https://github.com/roboticslab-uc3m/amor-main/commit/6242f5a8354eda589971f92f7f6dba0fa4cfd68b
   * https://github.com/roboticslab-uc3m/amor-configuration-files/commit/2c0e5afc9e79dd300111098597422fd97ca08d91 + https://github.com/roboticslab-uc3m/amor-configuration-files/commit/45b16d5d894c9559206cfd8c5487c41b66580dd2

**Comment by PeterBowman** [comment]
Eventually, language bindings will be moved to the [amor-api](https://github.com/roboticslab-uc3m/amor-api) private repo. The original issue has been reopened and repurposed: https://github.com/roboticslab-uc3m/amor-api/issues/5. See rationale at https://github.com/roboticslab-uc3m/amor-main/issues/1#issuecomment-398456136.
